[features]
seeds = false
skip-lint = false
[programs.localnet]
consensus_onchain = "B2fHGq6iwRPGmn3KBUFBgQpxVnDGFQT3ZjD2vJTDphZn"
[programs.devnet]
consensus_onchain = "B2fHGq6iwRPGmn3KBUFBgQpxVnDGFQT3ZjD2vJTDphZn"
[programs.mainnet]
consensus_onchain = "B2fHGq6iwRPGmn3KBUFBgQpxVnDGFQT3ZjD2vJTDphZn"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
